# Generated by Django 6.0.4 on 2026-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="garage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_heating",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_furnished",
            field=models.BooleanField(default=False),
        ),
    ]
