# Generated by Django 6.0.4 on 2026-04-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_garage_listing_has_ac_listing_has_heating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("rented", "Rented"),
                    ("pending", "Pending"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True)),
                ("contact_date", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
