# Generated by Django 6.0.4 on 2026-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_review_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
