# Generated by Django 6.0.4 on 2026-04-27 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_listing_is_verified_listing_views_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional rent discount shown to renters (e.g. 10 for 10%).",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "bonus_points_on_inquiry",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra reward points for logged-in users who send an inquiry during this promo.",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="PointsLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive for earned; negative when redeeming (future)."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("signup", "Welcome bonus"),
                            ("inquiry_sent", "Property inquiry"),
                            ("review_posted", "Review posted"),
                            ("favorite_added", "Saved favorite"),
                            ("listing_published", "Published listing"),
                            ("offer_inquiry_bonus", "Promo: inquiry bonus"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("balance_after", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_events",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Points entry",
                "verbose_name_plural": "Points ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=0)),
                ("lifetime_points", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward wallet",
                "verbose_name_plural": "Reward wallets",
            },
        ),
    ]
