# Generated by Django 6.0.4 on 2026-04-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_ai_assistant_daily"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="tenant_type",
            field=models.CharField(
                choices=[
                    ("bachelor", "Bachelor"),
                    ("family", "Family"),
                    ("any", "Any"),
                ],
                db_index=True,
                default="any",
                help_text="Who this rental best suits - bachelor flat vs family home, or any.",
                max_length=20,
            ),
        ),
    ]
