# Generated by Django 5.2.13 on 2026-08-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_city_choices_and_girl_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="address_verified",
            field=models.BooleanField(
                default=False, help_text="Address checked by admin."
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="availability_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Owner/landlord phone shown to renters; also used for verification and duplicate detection.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="document_checked",
            field=models.BooleanField(
                default=False,
                help_text="Owner/landlord document checked privately by admin. Not shown publicly.",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="main_image_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="photos_verified",
            field=models.BooleanField(
                default=False, help_text="Real property photos uploaded."
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rent_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="tenant_fit_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Free text, e.g. "Suitable for female students, small family, and job holders. Not allowed: bachelor male group."',
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="trust_score",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="image_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(blank=True, max_length=200)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fake", "Fake / misleading listing"),
                            ("fraud", "Fraud / scam"),
                            ("wrong_info", "Incorrect information"),
                            ("offensive", "Offensive content"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="listings.listing",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Dhaka", "Dhaka"),
                            ("Chittagong", "Chittagong"),
                            ("Sylhet", "Sylhet"),
                            ("Rajshahi", "Rajshahi"),
                            ("Khulna", "Khulna"),
                            ("Gazipur", "Gazipur"),
                            ("Mymensingh", "Mymensingh"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="hotels/"),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("list_date", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-list_date"],
            },
        ),
        migrations.CreateModel(
            name="ListingFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("phone_reuse", "Phone reused across many listings"),
                            ("address_price_mismatch", "Same address, different rents"),
                            ("low_rent_area", "Rent far below area average"),
                            ("text_similarity", "Very similar title/description"),
                            ("image_reuse", "Repeated image across listings"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="listings.listing",
                    ),
                ),
                (
                    "related_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("flat_owner", "Flat Owner"),
                            ("property_owner", "Property Owner"),
                            ("hotel_manager", "Hotel Manager"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Dhaka", "Dhaka"),
                            ("Chittagong", "Chittagong"),
                            ("Sylhet", "Sylhet"),
                            ("Rajshahi", "Rajshahi"),
                            ("Khulna", "Khulna"),
                            ("Gazipur", "Gazipur"),
                            ("Mymensingh", "Mymensingh"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "property_kind",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("land", "Land"),
                            ("house", "House"),
                            ("commercial", "Commercial space"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("square_feet", models.IntegerField()),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_sales/"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("under_negotiation", "Under negotiation"),
                            ("sold", "Sold"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("list_date", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-list_date"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True)),
                (
                    "offered_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="listings.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_sales/gallery/")),
                (
                    "property_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.propertylisting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_type", models.CharField(max_length=100)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=2)),
                ("total_rooms", models.PositiveSmallIntegerField(default=1)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="hotels/rooms/"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="listings.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("guests", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="listings.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
